### ISSUE TITLE
net/asterisk16 is broken

### ISSUE THREAD

**Issue by brad0** [opnsense/ports#91] opened 2020-05-18 01:35 UTC
After updating from OPNsense 20.1 to 20.7 I noticed my Asterisk setup is broken. Both were using asterisk16.

This is using asterisk16-16.9.0_1. But I see there is a port update to 16.10.0 plus a patch that might fix this. The current packages for 20.7 do not include this port update.

XSLT support not found. XML documentation may be incomplete.
PBX UUID: 133b5cd2-3ae4-4615-a9f4-6e6e7a632d3c
[May 17 21:04:19] NOTICE[100307]: loader.c:2377 int load_modules(void): 318 modules will be loaded.
[May 17 21:04:19] ERROR[100307]: res_config_sqlite.c:1680 int load_module(void): unable to open database: /var/lib/asterisk/sqlite.db
[May 17 21:04:19] WARNING[100307]: res_config_mysql.c:1247 int load_mysql_config(struct ast_config *, const char *, struct mysql_conn *): MySQL RealTime: No database user found, using 'asterisk' as default.
[May 17 21:04:19] WARNING[100307]: res_config_mysql.c:1253 int load_mysql_config(struct ast_config *, const char *, struct mysql_conn *): MySQL RealTime: No database password found, using 'asterisk' as default.
[May 17 21:04:19] WARNING[100307]: res_config_mysql.c:1259 int load_mysql_config(struct ast_config *, const char *, struct mysql_conn *): MySQL RealTime: No database host found, using localhost via socket.
[May 17 21:04:19] WARNING[100307]: res_config_mysql.c:1265 int load_mysql_config(struct ast_config *, const char *, struct mysql_conn *): MySQL RealTime: No database name found, using 'asterisk' as default.
[May 17 21:04:19] WARNING[100307]: res_config_mysql.c:1271 int load_mysql_config(struct ast_config *, const char *, struct mysql_conn *): MySQL RealTime: No database port found, using 3306 as default.
[May 17 21:04:19] WARNING[100307]: res_config_mysql.c:1288 int load_mysql_config(struct ast_config *, const char *, struct mysql_conn *): MySQL RealTime: No database socket found (and unable to detect a suitable path).
[May 17 21:04:19] NOTICE[100307]: cdr.c:4522 int cdr_toggle_runtime_options(void): CDR simple logging enabled.
[May 17 21:04:19] WARNING[100307]: res_phoneprov.c:1232 struct varshead *get_defaults(void): Unable to find a valid server address or name.
[May 17 21:04:19] NOTICE[100307]: res_smdi.c:1424 int load_module(void): No SMDI interfaces are available to listen on, not starting SMDI listener.
SIP channel loading...
[May 17 21:04:19] WARNING[100307]: sip/config_parser.c:817 void sip_parse_nat_option(const char *, struct ast_flags *, struct ast_flags *): nat=yes is deprecated, use nat=force_rport,comedia instead
[May 17 21:04:19] NOTICE[100307]: chan_sip.c:31946 struct sip_peer *build_peer(const char *, struct ast_variable *, struct ast_variable *, int, int): The 'username' field for sip peers has been deprecated in favor of the term 'defaultuser'
[May 17 21:04:19] WARNING[100307]: chan_sip.c:32450 void display_nat_warning(const char *, int, struct ast_flags *): !!! PLEASE NOTE: Setting 'nat' for a peer/user that differs from the  global setting can make
[May 17 21:04:19] WARNING[100307]: chan_sip.c:32451 void display_nat_warning(const char *, int, struct ast_flags *): !!! the name of that peer/user discoverable by an attacker. Replies for non-existent peers/users
[May 17 21:04:19] WARNING[100307]: chan_sip.c:32452 void display_nat_warning(const char *, int, struct ast_flags *): !!! will be sent to a different port than replies for an existing peer/user. If at all possible,
[May 17 21:04:19] WARNING[100307]: chan_sip.c:32453 void display_nat_warning(const char *, int, struct ast_flags *): !!! use the global 'nat' setting and do not set 'nat' per peer/user.
[May 17 21:04:19] WARNING[100307]: chan_sip.c:32454 void display_nat_warning(const char *, int, struct ast_flags *): !!! (config category='voipms' global force_rport='No' peer/user force_rport='Yes')
[May 17 21:04:19] NOTICE[100307]: chan_skinny.c:8459 int config_load(void): Configuring skinny from skinny.conf
[May 17 21:04:19] NOTICE[100307]: confbridge/conf_config_parser.c:2342 int verify_default_profiles(void): Adding default_menu menu to app_confbridge
[May 17 21:04:19] NOTICE[100307]: cdr_radius.c:264 int load_module(void): Cannot load radiusclient-ng configuration file /etc/radiusclient-ng/radiusclient.conf.
[May 17 21:04:19] NOTICE[100307]: cel_custom.c:95 int load_config(void): No mappings found in cel_custom.conf. Not logging CEL to custom CSVs.
[May 17 21:04:19] NOTICE[100307]: cel_radius.c:236 int load_module(void): Cannot load radiusclient-ng configuration file /etc/radiusclient-ng/radiusclient.conf.
[May 17 21:04:19] NOTICE[100307]: cel_tds.c:450 int tds_load_module(int): cel_tds has no global category, nothing to configure.
[May 17 21:04:19] WARNING[100307]: cel_tds.c:555 int load_module(void): cel_tds module had config problems; declining load
[May 17 21:04:19] WARNING[100307]: chan_unistim.c:7009 int reload_config(void): Your OS does not support IP_PKTINFO, you must set public_ip.
[May 17 21:04:19] NOTICE[100426]: chan_sip.c:24984 void handle_response_peerpoke(struct sip_pvt *, int, struct sip_request *): Peer '101' is now Reachable. (5ms / 2000ms)
[May 17 21:04:19] NOTICE[100426]: chan_sip.c:24984 void handle_response_peerpoke(struct sip_pvt *, int, struct sip_request *): Peer 'voipms' is now Reachable. (8ms / 2000ms)
[May 17 21:04:19] WARNING[100307]: loader.c:2381 int load_modules(void): Some non-required modules failed to load.
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'chan_pjsip.so': /usr/local/lib/asterisk/modules/chan_pjsip.so: Undefined symbol "ast_sip_cli_traverse_objects"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'func_pjsip_aor.so': /usr/local/lib/asterisk/modules/func_pjsip_aor.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'func_pjsip_contact.so': /usr/local/lib/asterisk/modules/func_pjsip_contact.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'func_pjsip_endpoint.so': /usr/local/lib/asterisk/modules/func_pjsip_endpoint.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_caller_id.so': /usr/local/lib/asterisk/modules/res_pjsip_caller_id.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_config_wizard.so': /usr/local/lib/asterisk/modules/res_pjsip_config_wizard.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_dialog_info_body_generator.so': /usr/local/lib/asterisk/modules/res_pjsip_dialog_info_body_generator.so: Undefined symbol "ast_sip_pubsub_register_body_generator"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_diversion.so': /usr/local/lib/asterisk/modules/res_pjsip_diversion.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_dlg_options.so': /usr/local/lib/asterisk/modules/res_pjsip_dlg_options.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_dtmf_info.so': /usr/local/lib/asterisk/modules/res_pjsip_dtmf_info.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_empty_info.so': /usr/local/lib/asterisk/modules/res_pjsip_empty_info.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_endpoint_identifier_anonymous.so': /usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_anonymous.so: Undefined symbol "ast_sip_register_endpoint_identifier_with_name"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_endpoint_identifier_user.so': /usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_user.so: Undefined symbol "ast_sip_register_endpoint_identifier_with_name"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_mwi.so': /usr/local/lib/asterisk/modules/res_pjsip_mwi.so: Undefined symbol "ast_sip_register_subscription_handler"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_mwi_body_generator.so': /usr/local/lib/asterisk/modules/res_pjsip_mwi_body_generator.so: Undefined symbol "ast_sip_pubsub_register_body_generator"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_nat.so': /usr/local/lib/asterisk/modules/res_pjsip_nat.so: Undefined symbol "pjsip_notify_method"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_notify.so': /usr/local/lib/asterisk/modules/res_pjsip_notify.so: Undefined symbol "ast_sip_push_task"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_outbound_publish.so': /usr/local/lib/asterisk/modules/res_pjsip_outbound_publish.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_endpoint_identifier_ip.so': /usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_ip.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_exten_state.so': /usr/local/lib/asterisk/modules/res_pjsip_exten_state.so: Undefined symbol "ast_sip_subscription_get_endpoint"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_header_funcs.so': /usr/local/lib/asterisk/modules/res_pjsip_header_funcs.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_history.so': /usr/local/lib/asterisk/modules/res_pjsip_history.so: Undefined symbol "PJ_AF_UNSPEC"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_logger.so': /usr/local/lib/asterisk/modules/res_pjsip_logger.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_messaging.so': /usr/local/lib/asterisk/modules/res_pjsip_messaging.so: Undefined symbol "ast_sip_register_service"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_one_touch_record_info.so': /usr/local/lib/asterisk/modules/res_pjsip_one_touch_record_info.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_outbound_authenticator_digest.so': /usr/local/lib/asterisk/modules/res_pjsip_outbound_authenticator_digest.so: Undefined symbol "ast_sip_register_outbound_authenticator"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_outbound_registration.so': /usr/local/lib/asterisk/modules/res_pjsip_outbound_registration.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_path.so': /usr/local/lib/asterisk/modules/res_pjsip_path.so: Undefined symbol "ast_sip_register_supplement"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_phoneprov_provider.so': /usr/local/lib/asterisk/modules/res_pjsip_phoneprov_provider.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_pidf_body_generator.so': /usr/local/lib/asterisk/modules/res_pjsip_pidf_body_generator.so: Undefined symbol "ast_sip_pubsub_register_body_generator"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_pidf_digium_body_supplement.so': /usr/local/lib/asterisk/modules/res_pjsip_pidf_digium_body_supplement.so: Undefined symbol "ast_sip_pubsub_register_body_supplement"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_pidf_eyebeam_body_supplement.so': /usr/local/lib/asterisk/modules/res_pjsip_pidf_eyebeam_body_supplement.so: Undefined symbol "ast_sip_pubsub_register_body_supplement"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_session.so': /usr/local/lib/asterisk/modules/res_pjsip_session.so: Undefined symbol "PJ_AF_INET"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_sips_contact.so': /usr/local/lib/asterisk/modules/res_pjsip_sips_contact.so: Undefined symbol "ast_sip_register_service"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_t38.so': /usr/local/lib/asterisk/modules/res_pjsip_t38.so: Undefined symbol "PJ_AF_INET"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_publish_asterisk.so': /usr/local/lib/asterisk/modules/res_pjsip_publish_asterisk.so: Undefined symbol "ast_sip_publish_client_alloc_datastore"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_pubsub.so': /usr/local/lib/asterisk/modules/res_pjsip_pubsub.so: Undefined symbol "PJ_GUID_STRING_LENGTH"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_refer.so': /usr/local/lib/asterisk/modules/res_pjsip_refer.so: Undefined symbol "pjsip_invite_method"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_registrar.so': /usr/local/lib/asterisk/modules/res_pjsip_registrar.so: Undefined symbol "pjsip_register_method"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_rfc3326.so': /usr/local/lib/asterisk/modules/res_pjsip_rfc3326.so: Undefined symbol "pjsip_bye_method"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_sdp_rtp.so': /usr/local/lib/asterisk/modules/res_pjsip_sdp_rtp.so: Undefined symbol "PJ_AF_INET"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_send_to_voicemail.so': /usr/local/lib/asterisk/modules/res_pjsip_send_to_voicemail.so: Undefined symbol "ast_sip_session_register_supplement_with_module"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_xpidf_body_generator.so': /usr/local/lib/asterisk/modules/res_pjsip_xpidf_body_generator.so: Undefined symbol "ast_sip_pubsub_register_body_generator"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_rtp_asterisk.so': /usr/local/lib/asterisk/modules/res_rtp_asterisk.so: Undefined symbol "PJ_AF_INET"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjproject.so': /usr/local/lib/asterisk/modules/res_pjproject.so: Undefined symbol "PJ_AF_INET"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip.so': /usr/local/lib/asterisk/modules/res_pjsip.so: Undefined symbol "PJ_AF_INET"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_acl.so': /usr/local/lib/asterisk/modules/res_pjsip_acl.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): Error loading module 'res_pjsip_authenticator_digest.so': /usr/local/lib/asterisk/modules/res_pjsip_authenticator_digest.so: Undefined symbol "ast_sip_get_sorcery"
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): res_config_sqlite declined to load.
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): cdr_radius declined to load.
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): cdr_tds declined to load.
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): cel_radius declined to load.
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): cel_tds declined to load.
[May 17 21:04:19] ERROR[100307]: loader.c:2396 int load_modules(void): chan_unistim declined to load.

**Comment by fichtner** [comment] 2020-05-18 15:21
Since we do not manage the port your best bet is https://bugs.freebsd.org/bugzilla/

I can only offer to remove the binary package from our build which is probably the wrong direction in your use case

**Comment by brad0** [comment] 2020-05-18 19:03
Ya, I figured as much. I was just about to file a FreeBSD bug report and then I thought I should try here first.

The current package set for 20.7 is not up to date with the latest in the OPNsense ports tree. I would prefer if a package set could be built with this commit specifically..
https://github.com/opnsense/ports/commit/bce55ef4601572dfc1a30e869950c3fb3389b56c#diff-f0516c017babc75ebfa6e62f77147395
and see if the helps or not. If not then I could file a bug report with FreeBSD.

**Comment by fichtner** [comment] 2020-05-25 06:23
@brad0 a new 20.7-BETA snapshot is available for (internal) testing. Can you try this new package?

https://pkg.opnsense.org/FreeBSD:12:amd64/snapshots/latest/All/asterisk16-16.10.0_2.txz

**Comment by brad0** [comment] 2020-05-27 05:37
Thanks. Unfortunately the port is still broken. I have filed a bug report upstream.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246764

**Comment by mmaridev** [comment] 2020-09-08 07:27
Can still reproduce this, looking for a fix.

**Comment by fichtner** [comment] 2020-09-08 08:10
Looking for help ;)

**Comment by fichtner** [comment] 2020-09-08 20:16
moving this to https://github.com/opnsense/ports/issues/95

**Closed by fichtner** 2020-09-08 20:16 UTC
Labels: support

**Comment by TheGrandWazoo** [comment] 2021-04-24 18:40
So, I believe you are missing the entire PJSIP lib. Usually it is built with the Asterisk package but I do not see it. Here is a lib of PJSIP file in OPNsense 20.1.9_1
```
root@sbc02:/usr/local/etc/asterisk # pkg list | grep pjsip
/usr/local/etc/asterisk/pjsip.conf.sample
/usr/local/etc/asterisk/pjsip_notify.conf.sample
/usr/local/etc/asterisk/pjsip_wizard.conf.sample
/usr/local/include/asterisk/res_pjsip.h
/usr/local/include/asterisk/res_pjsip_body_generator_types.h
/usr/local/include/asterisk/res_pjsip_cli.h
/usr/local/include/asterisk/res_pjsip_outbound_publish.h
/usr/local/include/asterisk/res_pjsip_presence_xml.h
/usr/local/include/asterisk/res_pjsip_pubsub.h
/usr/local/include/asterisk/res_pjsip_session.h
/usr/local/lib/asterisk/modules/chan_pjsip.so
/usr/local/lib/asterisk/modules/func_pjsip_aor.so
/usr/local/lib/asterisk/modules/func_pjsip_contact.so
/usr/local/lib/asterisk/modules/func_pjsip_endpoint.so
/usr/local/lib/asterisk/modules/res_hep_pjsip.so
/usr/local/lib/asterisk/modules/res_pjsip.so
/usr/local/lib/asterisk/modules/res_pjsip_acl.so
/usr/local/lib/asterisk/modules/res_pjsip_authenticator_digest.so
/usr/local/lib/asterisk/modules/res_pjsip_caller_id.so
/usr/local/lib/asterisk/modules/res_pjsip_config_wizard.so
/usr/local/lib/asterisk/modules/res_pjsip_dialog_info_body_generator.so
/usr/local/lib/asterisk/modules/res_pjsip_diversion.so
/usr/local/lib/asterisk/modules/res_pjsip_dlg_options.so
/usr/local/lib/asterisk/modules/res_pjsip_dtmf_info.so
/usr/local/lib/asterisk/modules/res_pjsip_empty_info.so
/usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_anonymous.so
/usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_ip.so
/usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_user.so
/usr/local/lib/asterisk/modules/res_pjsip_exten_state.so
/usr/local/lib/asterisk/modules/res_pjsip_header_funcs.so
/usr/local/lib/asterisk/modules/res_pjsip_history.so
/usr/local/lib/asterisk/modules/res_pjsip_logger.so
/usr/local/lib/asterisk/modules/res_pjsip_messaging.so
/usr/local/lib/asterisk/modules/res_pjsip_mwi.so
/usr/local/lib/asterisk/modules/res_pjsip_mwi_body_generator.so
/usr/local/lib/asterisk/modules/res_pjsip_nat.so
/usr/local/lib/asterisk/modules/res_pjsip_notify.so
/usr/local/lib/asterisk/modules/res_pjsip_one_touch_record_info.so
/usr/local/lib/asterisk/modules/res_pjsip_outbound_authenticator_digest.so
/usr/local/lib/asterisk/modules/res_pjsip_outbound_publish.so
/usr/local/lib/asterisk/modules/res_pjsip_outbound_registration.so
/usr/local/lib/asterisk/modules/res_pjsip_path.so
/usr/local/lib/asterisk/modules/res_pjsip_phoneprov_provider.so
/usr/local/lib/asterisk/modules/res_pjsip_pidf_body_generator.so
/usr/local/lib/asterisk/modules/res_pjsip_pidf_digium_body_supplement.so
/usr/local/lib/asterisk/modules/res_pjsip_pidf_eyebeam_body_supplement.so
/usr/local/lib/asterisk/modules/res_pjsip_publish_asterisk.so
/usr/local/lib/asterisk/modules/res_pjsip_pubsub.so
/usr/local/lib/asterisk/modules/res_pjsip_refer.so
/usr/local/lib/asterisk/modules/res_pjsip_registrar.so
/usr/local/lib/asterisk/modules/res_pjsip_rfc3326.so
/usr/local/lib/asterisk/modules/res_pjsip_sdp_rtp.so
/usr/local/lib/asterisk/modules/res_pjsip_send_to_voicemail.so
/usr/local/lib/asterisk/modules/res_pjsip_session.so
/usr/local/lib/asterisk/modules/res_pjsip_sips_contact.so
/usr/local/lib/asterisk/modules/res_pjsip_t38.so
/usr/local/lib/asterisk/modules/res_pjsip_transport_websocket.so
/usr/local/lib/asterisk/modules/res_pjsip_xpidf_body_generator.so
/usr/local/include/pjsip-simple/errno.h
/usr/local/include/pjsip-simple/evsub.h
/usr/local/include/pjsip-simple/evsub_msg.h
/usr/local/include/pjsip-simple/iscomposing.h
/usr/local/include/pjsip-simple/mwi.h
/usr/local/include/pjsip-simple/pidf.h
/usr/local/include/pjsip-simple/presence.h
/usr/local/include/pjsip-simple/publish.h
/usr/local/include/pjsip-simple/rpid.h
/usr/local/include/pjsip-simple/types.h
/usr/local/include/pjsip-simple/xpidf.h
/usr/local/include/pjsip-ua/sip_100rel.h
/usr/local/include/pjsip-ua/sip_inv.h
/usr/local/include/pjsip-ua/sip_regc.h
/usr/local/include/pjsip-ua/sip_replaces.h
/usr/local/include/pjsip-ua/sip_timer.h
/usr/local/include/pjsip-ua/sip_xfer.h
/usr/local/include/pjsip.h
/usr/local/include/pjsip/print_util.h
/usr/local/include/pjsip/sip_auth.h
/usr/local/include/pjsip/sip_auth_aka.h
/usr/local/include/pjsip/sip_auth_msg.h
/usr/local/include/pjsip/sip_auth_parser.h
/usr/local/include/pjsip/sip_autoconf.h
/usr/local/include/pjsip/sip_autoconf.h.in
/usr/local/include/pjsip/sip_config.h
/usr/local/include/pjsip/sip_dialog.h
/usr/local/include/pjsip/sip_endpoint.h
/usr/local/include/pjsip/sip_errno.h
/usr/local/include/pjsip/sip_event.h
/usr/local/include/pjsip/sip_module.h
/usr/local/include/pjsip/sip_msg.h
/usr/local/include/pjsip/sip_multipart.h
/usr/local/include/pjsip/sip_parser.h
/usr/local/include/pjsip/sip_private.h
/usr/local/include/pjsip/sip_resolve.h
/usr/local/include/pjsip/sip_tel_uri.h
/usr/local/include/pjsip/sip_transaction.h
/usr/local/include/pjsip/sip_transport.h
/usr/local/include/pjsip/sip_transport_loop.h
/usr/local/include/pjsip/sip_transport_tcp.h
/usr/local/include/pjsip/sip_transport_tls.h
/usr/local/include/pjsip/sip_transport_udp.h
/usr/local/include/pjsip/sip_types.h
/usr/local/include/pjsip/sip_ua_layer.h
/usr/local/include/pjsip/sip_uri.h
/usr/local/include/pjsip/sip_util.h
/usr/local/include/pjsip_auth.h
/usr/local/include/pjsip_simple.h
/usr/local/include/pjsip_ua.h
/usr/local/lib/libpjsip-amd64-portbld-freebsd11.2.a
/usr/local/lib/libpjsip-simple-amd64-portbld-freebsd11.2.a
/usr/local/lib/libpjsip-simple.so
/usr/local/lib/libpjsip-simple.so.2
/usr/local/lib/libpjsip-ua-amd64-portbld-freebsd11.2.a
/usr/local/lib/libpjsip-ua.so
/usr/local/lib/libpjsip-ua.so.2
/usr/local/lib/libpjsip.so
/usr/local/lib/libpjsip.so.2
/usr/local/share/licenses/pjsip-extsrtp-2.9_4/GPLv2+
/usr/local/share/licenses/pjsip-extsrtp-2.9_4/LICENSE
/usr/local/share/licenses/pjsip-extsrtp-2.9_4/catalog.mk
```

Compared to OPNsense 21.1.5
```
root@sbc01:/usr/local/etc/asterisk # pkg list | grep pjsip
/usr/local/etc/asterisk/pjsip.conf.sample
/usr/local/etc/asterisk/pjsip_notify.conf.sample
/usr/local/etc/asterisk/pjsip_wizard.conf.sample
/usr/local/include/asterisk/res_pjsip.h
/usr/local/include/asterisk/res_pjsip_body_generator_types.h
/usr/local/include/asterisk/res_pjsip_cli.h
/usr/local/include/asterisk/res_pjsip_outbound_publish.h
/usr/local/include/asterisk/res_pjsip_presence_xml.h
/usr/local/include/asterisk/res_pjsip_pubsub.h
/usr/local/include/asterisk/res_pjsip_session.h
/usr/local/lib/asterisk/modules/chan_pjsip.so
/usr/local/lib/asterisk/modules/func_pjsip_aor.so
/usr/local/lib/asterisk/modules/func_pjsip_contact.so
/usr/local/lib/asterisk/modules/func_pjsip_endpoint.so
/usr/local/lib/asterisk/modules/res_hep_pjsip.so
/usr/local/lib/asterisk/modules/res_pjsip.so
/usr/local/lib/asterisk/modules/res_pjsip_acl.so
/usr/local/lib/asterisk/modules/res_pjsip_authenticator_digest.so
/usr/local/lib/asterisk/modules/res_pjsip_caller_id.so
/usr/local/lib/asterisk/modules/res_pjsip_config_wizard.so
/usr/local/lib/asterisk/modules/res_pjsip_dialog_info_body_generator.so
/usr/local/lib/asterisk/modules/res_pjsip_diversion.so
/usr/local/lib/asterisk/modules/res_pjsip_dlg_options.so
/usr/local/lib/asterisk/modules/res_pjsip_dtmf_info.so
/usr/local/lib/asterisk/modules/res_pjsip_empty_info.so
/usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_anonymous.so
/usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_ip.so
/usr/local/lib/asterisk/modules/res_pjsip_endpoint_identifier_user.so
/usr/local/lib/asterisk/modules/res_pjsip_exten_state.so
/usr/local/lib/asterisk/modules/res_pjsip_header_funcs.so
/usr/local/lib/asterisk/modules/res_pjsip_history.so
/usr/local/lib/asterisk/modules/res_pjsip_logger.so
/usr/local/lib/asterisk/modules/res_pjsip_messaging.so
/usr/local/lib/asterisk/modules/res_pjsip_mwi.so
/usr/local/lib/asterisk/modules/res_pjsip_mwi_body_generator.so
/usr/local/lib/asterisk/modules/res_pjsip_nat.so
/usr/local/lib/asterisk/modules/res_pjsip_notify.so
/usr/local/lib/asterisk/modules/res_pjsip_one_touch_record_info.so
/usr/local/lib/asterisk/modules/res_pjsip_outbound_authenticator_digest.so
/usr/local/lib/asterisk/modules/res_pjsip_outbound_publish.so
/usr/local/lib/asterisk/modules/res_pjsip_outbound_registration.so
/usr/local/lib/asterisk/modules/res_pjsip_path.so
/usr/local/lib/asterisk/modules/res_pjsip_phoneprov_provider.so
/usr/local/lib/asterisk/modules/res_pjsip_pidf_body_generator.so
/usr/local/lib/asterisk/modules/res_pjsip_pidf_digium_body_supplement.so
/usr/local/lib/asterisk/modules/res_pjsip_pidf_eyebeam_body_supplement.so
/usr/local/lib/asterisk/modules/res_pjsip_publish_asterisk.so
/usr/local/lib/asterisk/modules/res_pjsip_pubsub.so
/usr/local/lib/asterisk/modules/res_pjsip_refer.so
/usr/local/lib/asterisk/modules/res_pjsip_registrar.so
/usr/local/lib/asterisk/modules/res_pjsip_rfc3326.so
/usr/local/lib/asterisk/modules/res_pjsip_sdp_rtp.so
/usr/local/lib/asterisk/modules/res_pjsip_send_to_voicemail.so
/usr/local/lib/asterisk/modules/res_pjsip_session.so
/usr/local/lib/asterisk/modules/res_pjsip_sips_contact.so
/usr/local/lib/asterisk/modules/res_pjsip_stir_shaken.so
/usr/local/lib/asterisk/modules/res_pjsip_t38.so
/usr/local/lib/asterisk/modules/res_pjsip_transport_websocket.so
/usr/local/lib/asterisk/modules/res_pjsip_xpidf_body_generator.so
```

If you notice, it is missing the underlying PJSIP libs "/usr/local/lib/libpjsip*" and the includes.

So either the flag to build the PJSIP libs with Asterisk is turned OFF, or you need to also build the FreeBSD net/pjsip package so it can be installed with Asterisk. 

I elect to flag it on the build with Asterisk, because they usually develop to a certain version.
